name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf1e481913efd8260a353e87a51ac68630f303b7f653edf01a2b1930e9966f0c"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
