name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5abd5eab927b075451c3868f92323bb441b41cfd78c446a52a8c498a63b6218c"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
