name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41624aba3c82d704eda5a7141c64e59bedb14361ae5bea4fbe6096cfe0feb2f1"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
