name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "290be98bca44f21c53d470234194084543e39540d05411b74c2453be7a4ae520"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
