name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ff2c757a623f2ad0dee9b1175ba1f75705f02d606b223b6f9ad07d5952ca3b"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
