name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afd3d2c93eb2f12130e30f4d2dc8bb58e2b21dac167273c5c4b71f336351bf8c"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
