name = "Innerrealm"
author = "Veselle"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654d1e01f4800f0c4863c6616dd0e67f52fb8837f822db356a91b6a6a95c971a"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
